-- CREATED TABLE 1
CREATE TABLE MATCHES (
	ID SERIAL NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	DATE DATE NOT NULL,
	PLAYER_OF_MATCH TEXT NOT NULL,
	VENUE TEXT NOT NULL,
	NEUTRAL_VENUE INT2,
	TEAM1 VARCHAR(100) NOT NULL,
	TEAM2 VARCHAR(100) NOT NULL,
	TOSS_WINNER VARCHAR(100) NOT NULL,
	TOSS_DECISION CHAR(6) NOT NULL,
	WINNER VARCHAR(100) NOT NULL,
	RESULT CHAR(8) NOT NULL,
	RESULT_MARGIN INT2,
	ELIMINATOR CHAR(2),
	METHOD CHAR(4),
	UMPIRE1 TEXT NOT NULL,
	UMPIRE2 TEXT NOT NULL,
	PRIMARY KEY(ID),
	CONSTRAINT NUMERIC_VALUE CHECK(
		ID > 0
		AND RESULT_MARGIN > 0
		AND (
			NEUTRAL_VENUE = 0
			OR NEUTRAL_VENUE = 1
		)
	)
);

-- CREATED TABLE 2
CREATE TABLE DELIVIERIES (
	ID SERIAL NOT NULL,
	INNING INT2,
	OVER INT2,
	BALL INT2,
	BATSMAN TEXT NOT NULL,
	NON_STRIKER TEXT NOT NULL,
	BOWLER TEXT NOT NULL,
	BATSMAN_RUNS INT2,
	EXTRA_RUNS INT2,
	TOTAL_RUNS INT NOT NULL,
	IS_WICKET INT2,
	DISMISSAL_KIND VARCHAR(50),
	PLAYER_DISMISSED TEXT,
	FIELDER TEXT,
	EXTRAS_TYPE VARCHAR(10),
	BATTING_TEAM TEXT NOT NULL,
	BOWLING_TEAM TEXT NOT NULL,
	CONSTRAINT ID_VALUE CHECK(ID > 0)
);

-- FETCH DATA FOR TABLE 1
COPY MATCHES
FROM
	'C:\Users\Desktop\IPL_Database\IPL_matches_record.csv' CSV HEADER;

-- FETCH DATA FOR TABLE 2
COPY DELIVIERIES
FROM
	'C:\Users\Desktop\IPL_Database\IPL_Balls_deliveries.csv' CSV HEADER;
